# Workflow for creating llvm artefacts
name: create llvm artefacts
on:
  workflow_call:
    inputs:
      llvm_branch:
        required: false
        type: string
      llvm_version:
        required: true
        type: string
        description: 'llvm (major) version - 20, 21 or main'
      use_github_cache:
        required: false
        type: boolean
        default: false
      target_list:
        type: string
        description: "List of targets (not LLVM targets, test targets e.g. host_aarch64_linux)"
        required: true
permissions: {}

jobs:
  create_llvm_artifacts_ubuntu_22_x86_64:
    # Need to build this for all linux targets.
    # TODO: Review if we can skip for riscv64
    if: contains(inputs.target_list, '_linux')
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo ock platform
        uses: actions/checkout@v4
      - name: build llvm artefact
        uses: ./.github/actions/do_build_llvm
        with:
          llvm_branch: ${{ inputs.llvm_branch }}
          llvm_version: ${{ inputs.llvm_version }}
          os: ubuntu-22.04
          use_github_cache: ${{ inputs.use_github_cache }}

  create_llvm_artifacts_ubuntu_24_x86_64:
    # We only currently need this for riscv64 jobs
    if: contains(inputs.target_list, 'host_riscv64_linux')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo ock platform
        uses: actions/checkout@v4
      - name: build llvm artefact
        uses: ./.github/actions/do_build_llvm
        with:
          llvm_branch: ${{ inputs.llvm_branch }}
          llvm_version: ${{ inputs.llvm_version }}
          os: ubuntu-24.04
          use_github_cache: ${{ inputs.use_github_cache }}

  create_llvm_artifacts_ubuntu_22_x86:
    if: contains(inputs.target_list, 'host_i686_linux')
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo ock platform
        uses: actions/checkout@v4
      - name: build llvm artefact
        uses: ./.github/actions/do_build_llvm
        with:
          llvm_branch: ${{ inputs.llvm_branch }}
          llvm_version: ${{ inputs.llvm_version }}
          os: ubuntu-22.04
          arch: x86
          use_github_cache: ${{ inputs.use_github_cache }}

  create_llvm_artifacts_ubuntu_22_aarch64:
    if: contains(inputs.target_list, 'host_aarch64_linux')
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo ock platform
        uses: actions/checkout@v4
      - name: build llvm artefact
        uses: ./.github/actions/do_build_llvm
        with:
          llvm_branch: ${{ inputs.llvm_branch }}
          llvm_version: ${{ inputs.llvm_version }}
          os: ubuntu-22.04
          arch: aarch64
          use_github_cache: ${{ inputs.use_github_cache }}

  create_llvm_artifacts_ubuntu_24_riscv64:
    if: contains(inputs.target_list, 'host_riscv64_linux')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo ock platform
        uses: actions/checkout@v4
      - name: build llvm artefact
        uses: ./.github/actions/do_build_llvm
        with:
          llvm_branch: ${{ inputs.llvm_branch }}
          llvm_version: ${{ inputs.llvm_version }}
          os: ubuntu-24.04
          arch: riscv64
          use_github_cache: ${{ inputs.use_github_cache }}

  create_llvm_artifacts_windows_2025_x86_64:
    if: contains(inputs.target_list, 'host_x86_64_windows')
    runs-on: windows-2025
    steps:
      - name: Checkout repo ock platform
        uses: actions/checkout@v4
      - name: build llvm artefact
        uses: ./.github/actions/do_build_llvm
        with:
          llvm_branch: ${{ inputs.llvm_branch }}
          llvm_version: ${{ inputs.llvm_version }}
          os: 'windows-2025'
          use_github_cache: ${{ inputs.use_github_cache }}
