# Simple workflow for building documentation for PR testing
name: Build documentation

# On a pull request this will build the html documentation
# and create an artifact. It does this by using the cmake
# build target doc_html. Note that this requires installing a little
# more than is technically required for building the documentation in
# order to satisfy our current cmake configurations e.g. spirv-tools
on:
  pull_request:
    paths:
      - doc/**
      - .github/workflows/docs.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: 3.9

      - name: Install apt package
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen virtualenv

      - name: Install prerequisites
        run: python -m pip install -r doc/requirements.txt

      - name: Build Documentation
        working-directory: ${{github.workspace}}
        run: |
          cmake -DCA_ENABLE_API=cl -DCMAKE_BUILD_TYPE=Debug -DCA_RUNTIME_COMPILER_ENABLED=OFF -DCA_CL_ENABLE_OFFLINE_KERNEL_TESTS=OFF -DOCL_EXTENSION_cl_khr_il_program=OFF -Bbuild_doc
          cmake --build build_doc --target doc_html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: ${{github.workspace}}/build_doc/doc/html
