name: run planned tests for experimental llvm main
on:
  pull_request:
    paths:
      - '.github/workflows/planned_testing_caller_main.yml'
  schedule:
    # Run Mon-Fri at 6am
    - cron: '0 6 * * 1,2,3,4,5'

permissions:
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # This makes the diagram too big if we post much here so Lmainexp_ is used.
  Lmainexp_:
    if: github.repository == 'uxlfoundation/oneapi-construction-kit' || github.event_name != 'schedule'
    uses: ./.github/workflows/planned_testing_caller.yml
    with:
      llvm_version: 'main'
      llvm_branch: 'main'
      save_cache:  ${{ github.event_name == 'schedule' }}
      target_list: '[ "host_x86_64_linux", "refsi_riscv64_linux" ]'
      ock: true
      native_cpu: false
      test_tornado: false
      test_remote_hal: false
      test_sycl_cts: false
      test_sycl_e2e: false
      test_opencl_cts: false
      run_internal: true
      run_external: false
      build_llvm: true

  # If this is extended to include dpc++ building, then copy clean_caches from one of the other
  # planned_testing files
